name: Job Automation

on:
  schedule:
    - cron: '30 0 * * *'
    - cron: '30 15 * * *'

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python app.py

        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}